projects:

  tg-repo-watcher:
    repo: arkhivar/tg-repo-watcher
    chat_id: -1003947505610
    thread_id: 10
    trigger: webhook
    
  qr-rf:
    repo: arkhivar/qr-rf
    chat_id: -1003947505610
    thread_id: 23
    trigger: webhook

  se-download:
    repo: arkhivar/se-download
    chat_id: -1003947505610
    thread_id: 19
    trigger: webhook

  tax-deduction:
    repo: arkhivar/tax-deduction
    chat_id: -1003947505610
    thread_id: 17
    trigger: webhook
    
  recipes:
    repo: arkhivar/recipes
    chat_id: -1003947505610
    thread_id: 15
    trigger: webhook

  outline-plasmoid:
    repo: arkhivar/outline-plasmoid
    chat_id: -1003947505610
    thread_id: 12
    trigger: webhook

  vpn-zona:
    repo: arkhivar/vpn-zona
    chat_id: -1003947505610
    thread_id: 8
    trigger: webhook

  premises-web:
    repo: arkhivar/premises-web
    chat_id: -1003947505610
    thread_id: 2
    trigger: webhook
